# -*- coding: utf-8 -*-
"""version3_file_input_single.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14oaS0mFQoegzhOwEz7C1PM4CmfTyF0GJ
"""

# Version 3: Read coefficients and time from a file

with open("input_single.txt", "r") as f:
    lines = f.read().splitlines()

# Extract coefficients and time
a = float(lines[0])
b = float(lines[1])
c = float(lines[2])
t = float(lines[3])

# Quadratic formula
T = a * (t**2) + b * t + c

print(f"Predicted Temperature at t={t} is: {T}")