# -*- coding: utf-8 -*-
"""version4_file_input_multiple.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Z67eZhzw9jW4RP7ex-g5ji5SSzupF8d
"""

# Version 4: Read multiple sets of coefficients and time from a file

with open("input_multiple.txt", "r") as f:
    lines = f.read().splitlines()

# Process each line (each set of a, b, c, t)
for line in lines:
    a, b, c, t = map(float, line.split())

    # Quadratic formula
    T = a * (t**2) + b * t + c

    print(f"For coefficients (a={a}, b={b}, c={c}) at t={t}, "
          f"Predicted Temperature = {T}")