# -*- coding: utf-8 -*-
"""version2_keyboard_input.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSxrKAokHq_glhJBeaugNvhqPcf63K6V
"""

# Version 2: Keyboard input

# Take inputs from user
a = float(input("Enter coefficient a: "))
b = float(input("Enter coefficient b: "))
c = float(input("Enter coefficient c: "))
t = float(input("Enter time t (in hours/days): "))

# Quadratic formula
T = a * (t**2) + b * t + c

print(f"Predicted Temperature at t={t} is: {T}")