# -*- coding: utf-8 -*-
"""version1_hardcoded.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbL0pc3xPnU1efpOpSzG9W-8HJclBglu
"""

#Version -1 HardCoded Values

# Hardcoded coefficients and time
a = 2
b = -3
c = 5
t = 4   # example time

# Quadratic formula
T = a * (t**2) + b * t + c

print(f"Predicted Temperature at t={t} is: {T}")